import { methods } from './utils/type';
export declare const AllMethods: methods[];
export declare const SortList: string[];
export declare const NotModifyCode = "/* tslint:disable */\n/**\n* This file was automatically generated by openapi-gen-typescript.\n* DO NOT MODIFY IT BY HAND.\n*/\n";
export declare enum ETemplateCode {
    RequestUrl = "requestUrl",
    requestPathCode = "requestPathCode",
    RequestQueryCode = "requestQueryCode",
    RequestHeaderCode = "requestHeaderCode",
    RequestCookieCode = "requestCookieCode",
    RequestBodyCode = "requestBodyCode",
    ResponsesCode = "responsesCode",
    RequestFuncTypeCode = "requestFuncTypeCode"
}
